default: &default
  adapter: <%= ENV.fetch('DATABASE_ADAPTER', 'postgresql') %>
  encoding: utf8
  support_json: <%= ENV.fetch('DATABASE_SUPPORT_JSON', 'true') %>
  <% if ENV.key?('DATABASE_COLLATION') %>
  collation: <%= ENV.fetch('DATABASE_COLLATION', 'en_US.utf8') %>
  <% end %>
  pool: <%= ENV.fetch('DATABASE_POOL', ENV.fetch("RAILS_MAX_THREADS", 8).to_i * ENV.fetch("WEB_CONCURRENCY", 1).to_i + 2) %>
  <% if ENV.key?('DATABASE_HOST') %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  <% end %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  <% if ENV.key?('DATABASE_USER') %>
  username: <%= ENV.fetch('DATABASE_USER', `whoami`.chomp) %>
  <% end %>
  <% if ENV.key?('DATABASE_PASS') %>
  password: <%= ENV['DATABASE_PASS'] %>
  <% end %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'peatio_development') %>

test:
  <<: *default
  database: peatio_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'peatio_staging') %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'peatio_production') %>

sandbox:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'peatio_sandbox') %>

archive_db:
  <<: *default
  url: <%= ENV['ARCHIVE_DATABASE_URL'] %>
  database: <%= ENV.fetch('ARCHIVE_DATABASE_NAME', 'peatio_archive_db') %>
  username: <%= ENV.fetch('ARCHIVE_DATABASE_USER', 'root') %>
  password: <%= ENV['ARCHIVE_DATABASE_PASS'] %>
  host: <%= ENV.fetch('ARCHIVE_DATABASE_HOST', '127.0.0.1') %>

belomor_development:
  <<: *default
  database: belomor_development

belomor_test:
  <<: *default
  database: belomor_test

belomor_production:
  <<: *default
  url: <%= ENV['BELOMOR_DATABASE_URL'] %>
