- key:               bitzlato
  name:              Bitzlato P2P
  gateway_klass:     BitzlatoGateway                 # API client name.
  server:            http://127.0.0.1:8545  # Public Ethereum node endpoint. IMPORTANT: full syncmode.
  height:            1
  min_confirmations: 1                      # Minimal confirmations needed for withdraw and deposit confirmation.
  status:            disabled

- key:               prt-kovan
  name:              Ethereum Kovan
  gateway_klass:     EthereumGateway                 # API client name.
  server:            http://127.0.0.1:8545  # Public Ethereum node endpoint. IMPORTANT: full syncmode.
  height:            2500000                # Initial block number from which sync will be started.
  min_confirmations: 6                      # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://kovan.etherscan.io/address/#{address}
    transaction:     https://kovan.etherscan.io/tx/#{txid}
  status:            disabled

- key:               eth-rinkeby
  name:              Ethereum Rinkeby
  gateway_klass:     EthereumGateway                 # API client name.
  server:            http://127.0.0.1:8545  # Public Ethereum node endpoint. IMPORTANT: full syncmode.
  height:            4000000                # Initial block number from which sync will be started.
  min_confirmations: 6                      # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://rinkeby.etherscan.io/address/#{address}
    transaction:     https://rinkeby.etherscan.io/tx/#{txid}
  status:            active

- key:               eth-mainnet
  name:              Ethereum Mainet
  gateway_klass:     EthereumGateway                 # API client name.
  server:            http://127.0.0.1:8545  # Public Ethereum node endpoint. IMPORTANT: full syncmode.
  height:            7500000                # Initial block number from which sync will be started.
  min_confirmations: 6                      # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://etherscan.io/address/#{address}
    transaction:     https://etherscan.io/tx/#{txid}
  status:            disabled

- key:               btc-testnet
  name:              Bitcoin Testnet
  gateway_klass:     BitcoinGateway                 # API client name.
  server:            http://user:password@127.0.0.1:18332 # Public Bitcoin node endpoint.
  height:            1500000                              # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://testnet.blockchain.info/address/#{address}
    transaction:     https://testnet.blockchain.info/tx/#{txid}
  status:            active

- key:               bsc-testnet
  name:              BSC Testnet
  gateway_klass:     EthereumGateway
  height:            13300000
  min_confirmations: 6
  explorer:
    address:         https://testnet.bscscan.com/address/#{address}
    transaction:     https://testnet.bscscan.com/tx/#{txid}
    contract_address: https://testent.bscscan.com/token/#{contract_address}
  status:            active
  client_options:
    gas_factor:      1
